export const SWITCH_TEMPERATURE_UNITS = "SWITCH_TEMPERATURE_UNITS";

export const GET_ALL_CITIES_SUCCESSFUL = "GET_ALL_CITIES_SUCCESSFUL";
export const GET_CITY_SUCCESSFUL = "GET_CITY_SUCCESSFUL";
export const DELETE_CITY_SUCCESSFUL = "DELETE_CITY_SUCCESSFUL";
